import Header from "./components/Header"
import "./globals.css"
import Footer from "./components/Footer"

export const metadata = {
  title: "E-commerce Store | Discover Our Products",
  description: "Browse our collection of high-quality products including bags, toys, and accessories.",
  openGraph: {
    title: "E-commerce Store | Discover Our Products",
    description: "Browse our collection of high-quality products including bags, toys, and accessories.",
    //images: ["/og-image.jpg"],
  },
  schema: {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "E-commerce Store",
    url: "https://example.com",
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

























// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
